// <auto-generated />
using System;
using DSAapp.Core.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSAapp.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DSAapp.Core.Models.ComentarioOficio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OficioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OficioId");

                    b.ToTable("ComentariosOficio");
                });

            modelBuilder.Entity("DSAapp.Core.Models.Oficio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BloqueadoDesde")
                        .HasColumnType("TEXT");

                    b.Property<string>("BloqueadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("CadidoFondo")
                        .HasColumnType("TEXT");

                    b.Property<string>("CadidoSeccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("CadidoSerie")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapturadoPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolioInterno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolioOriginal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remitente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaArchivoRed")
                        .HasColumnType("TEXT");

                    b.Property<string>("UbicacionCaja")
                        .HasColumnType("TEXT");

                    b.Property<string>("UbicacionEstante")
                        .HasColumnType("TEXT");

                    b.Property<string>("UbicacionLefort")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioAsignado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Oficios");
                });

            modelBuilder.Entity("DSAapp.Core.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaCompletada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaArchivoAdjunto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TareasInstitucionales", (string)null);
                });

            modelBuilder.Entity("DSAapp.Core.Models.ComentarioOficio", b =>
                {
                    b.HasOne("DSAapp.Core.Models.Oficio", "Oficio")
                        .WithMany("Comentarios")
                        .HasForeignKey("OficioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oficio");
                });

            modelBuilder.Entity("DSAapp.Core.Models.Oficio", b =>
                {
                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
